export const colors = {
  primary: '#005bbf',
  primaryContainer: '#1a73e8',
  onPrimary: '#ffffff',
  secondary: '#855300',
  secondaryContainer: '#fea619',
  onSecondary: '#ffffff',
  background: '#f7f9fb',
  surface: '#ffffff',
  surfaceContainer: '#eceef0',
  surfaceContainerLow: '#f4f6f8',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerHigh: '#e1e3e5',
  surfaceContainerHighest: '#d7d9db',
  onSurface: '#191c1e',
  onSurfaceVariant: '#414754',
  outline: '#727785',
  error: '#ba1a1a',
  onError: '#ffffff',
  success: '#10b981', // Added for stock status
};
